# Generated by Django 4.1.4 on 2023-01-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_cat_feeding_horse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='horse',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
